name: Push Templates to Database

on:
  push:
    branches: [ main, str ]
    
jobs:
  action-PushTemplatesToDB:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install NSwag CLI
        run: dotnet tool install --global NSwag.ConsoleCore

      - name: Generate NSwag Client
        run: |
          nswag openapi2csclient /input:https://str.nfdi4plants.org/swagger/v1/swagger.json /output:src/STRCI/STRClient.cs /namespace:STRClient

      - name: Push missing templates to Database
        env:
          STR_PAT: ${{ secrets.STR_PAT }}
        run: dotnet run --project src/STRCI/STRCI.fsproj
