name: Release json file

on:
  push:
    branches: [ main ]
    
jobs:

  release-github:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: convert and publish 1.0.0
      run: dotnet fsi release/templates-to-json_v1.0.0.fsx
    - name: convert and publish 2.0.0
      env:
        STR_PAT: ${{ secrets.STR_PAT }}
      run: dotnet run --project src/STRCI/STRCI.fsproj -- Release_2.0.0
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Template Json"
        files: |
            templates-to-json/report.txt
            templates-to-json/templates.json
            templates-to-json/report_v2.0.0.txt
            templates-to-json/templates_v2.0.0.json
