name: Release github

on:
  push:
    branches: [ main ]
    
jobs:

  release-github:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: convert and publish 1.0.0
      run: dotnet run --project src/STRCI/STRCI.fsproj -- Release_1.0.0
    - name: convert and publish 2.0.0
      run: dotnet run --project src/STRCI/STRCI.fsproj -- Release_2.0.0
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Template Json"
        files: |
            templates-to-json/report_v1.0.0.txt
            templates-to-json/templates_v1.0.0.json
            templates-to-json/report_v2.0.0.txt
            templates-to-json/templates_v2.0.0.json
