name: Release github

on:
  push:
    branches: [ main ]
  pull_request:
jobs:

  release-github:
    
    runs-on: ubuntu-latest

    steps:
    - name: convert and publish 1.0.0
      run: dotnet run --project src/STRCI/STRCI.fsproj -- Release_1.0.0
