name: Release github

on:
  push:
    branches: [ main ]
  pull_request:
jobs:

  release-github:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: convert and publish 1.0.0
      env:
        STR_PAT: ${{ secrets.STR_PAT }}
      run: dotnet run --project src/STRCI/STRCI.fsproj -- Release_1.0.0
