name: Test templates

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    
jobs:
  
  test-QualityEnsurace:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # or whatever version you're targeting
          
      - name: "[Test] qualityEnsurace"
        run: dotnet run --project tests/STRTest/STRTest.fsproj
